name: Release

on:
  push:
    branches: [main]
    paths:
      - 'package.json'

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-actions]')"
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Extracted version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Create Git Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "v${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          name: "Release v${{ steps.version.outputs.version }}"
          body: |
            Automatisches Release für Version ${{ steps.version.outputs.version }}
            Änderungen:
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
